name: Build-Test-Lint (win32)

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["{{cookiecutter.python_version}}"]
#        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v4
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
        cache: 'pip'
    - run: |
        .\ci\win32\create_venv.cmd
        .\ci\win32\install_dependencies.cmd

    - name: run unit tests
      run: |
        .\ci\win32\test_unit.cmd

    - name: Lint
      run: |
        .\ci\win32\lint.cmd
